### ISSUE TITLE
[Version: 0.1.0] TO-DO List

### ISSUE THREAD

**Issue by Devwarlt** [Devwarlt/robotop#1]
## Useful references
- [**[1][ref-1]**] Robocode 1.9.3.0 API
- [**[2][ref-2]**] RoboWiki
- [**[3][ref-3]**] Rock 'em, sock 'em Robocode!
- [**[4][ref-4]**] Anti Gravity + Wavesurfing Bot (used in Robocode tournaments)
- [**[5][ref-5]**] Melee Strategy

## TO-DO
- [x] setup basic project (Eclipse schema)
- [x] implement **[`Robocode API`][ref-1]** reference into project
- [x] setup basic project with sample robot using new imported API dependencies
- [x] setup project architecture pattern
- [x] implement basic robot behaviors
- [x] test robot behavior and report results

[ref-1]: https://robocode.sourceforge.io/docs/robocode/
[ref-2]: http://robowiki.net/
[ref-3]: https://www.ibm.com/developerworks/library/j-robocode/index.html
[ref-4]: https://github.com/parthnan/AntiGrav-WavesurfingBot
[ref-5]: http://robowiki.net/wiki/Melee_Strategy
