### ISSUE TITLE
[Version: 0.1.1] TO-DO List

### ISSUE THREAD

**Issue by Devwarlt** [Devwarlt/robotop#3]
## Useful references
- [**[1][ref-1]**] Melee Strategy

## TO-DO
- [x] develop a new strategy for Robotop where new behaviors will be integrated to robot itself
- [ ] work on strategy algorithm chart that'll be implemented in Robotop
- [ ] work on strategy manager handler (scratch idea for class **`StrategyManager`**) used to maintain always updated current Robotop behavior during battleship
- [ ] work on `StrategyManager` structure pattern using Robobot API reference and if necessary start utility class (scratch idea for class **`Utils`**)

[ref-1]: http://robowiki.net/wiki/Melee_Strategy
